name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - v*.*.*
  pull_request:
    branches:
      - 'main'

jobs:
  release:
    name: Releases
    runs-on: macos-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "Doordeck Development"
          git config --global user.email "development@doordeck.com"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Install SWIG
        run: brew install swig

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Tag for release (if on main)
        if: github.ref == 'refs/heads/main'
        run: ./gradlew final -x test

      - name: Parse release version
        id: version_info
        run: echo version=$(./gradlew properties -q -Prelease.useLastTag=true | grep "version:" | awk '{print $2}') >> "$GITHUB_OUTPUT"

      - name: Build mingw binaries
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew mingwX64Binaries
          
          # Adjust generated header
          sed -i '' \
            -e 's/_\$$/_/g' \
            -e 's/\$//g' \
            -e '/#ifndef _MSC_VER/{:a;N;/#endif/!ba;s/#ifndef _MSC_VER.*#endif/#ifdef SWIG\ntypedef float Doordeck_Headless_Sdk_KVector128[4];\n#else\n#ifndef _MSC_VER\ntypedef float __attribute__ ((__vector_size__ (16))) Doordeck_Headless_Sdk_KVector128;\n#else\n#include <xmmintrin.h>\ntypedef __m128 Doordeck_Headless_Sdk_KVector128;\n#endif\n#endif/}' \
          "doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk_api.h"

      - name: Publish to PyPi
        run: |
          ./gradlew pythonPack
          
          swig -python -o doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk/doordeck_headless_sdk_wrap.py \
            doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk/doordeck_headless_sdk.i

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v${{ steps.version_info.outputs.version }} --title "Release v${{ steps.version_info.outputs.version }}" --verify-tag --generate-notes