name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - v*.*.*
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check SPM publication
        id: check_spm_publication
        run: |
          if aws s3 ls s3://cdn.doordeck.com/xcframework/v1.0.0/ > /dev/null 2>&1; then
            echo spmPublished=true >> $GITHUB_OUTPUT
          else
            echo spmPublished=false >> $GITHUB_OUTPUT
          fi
          echo "The value of spmPublished is: ${{steps.check_spm_publication.outputs.spmPublished}}"