name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - v*.*.*
  pull_request:
    branches:
      - 'main'

jobs:
  release:
    name: Releases
    runs-on: macos-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "Doordeck Development"
          git config --global user.email "development@doordeck.com"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Print stuff
        run: |
          python3 -c "import sysconfig; print(sysconfig.get_paths()['include'])"
          python3 -c "import sysconfig; print(sysconfig.get_paths()['stdlib'])"

      - name: Install SWIG
        run: brew install swig

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Tag for release (if on main)
        if: github.ref == 'refs/heads/main'
        run: ./gradlew final -x test

      - name: Parse release version
        id: version_info
        run: echo version=$(./gradlew properties -q -Prelease.useLastTag=true | grep "version:" | awk '{print $2}') >> "$GITHUB_OUTPUT"

      - name: Build mingw binaries
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew mingwX64Binaries
          
          # Adjust generated header
          sed -i '' \
            -e 's/_\$$/_/g' \
            -e 's/\$//g' \
          "doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk_api.h"

      - name: Publish to PyPi
        run: |
          ./gradlew pythonPack
          
          swig -python -D_MSC_VER -o doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk/doordeck_headless_sdk_wrap.c \
            doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk/doordeck_headless_sdk.i
          
          gcc -shared -o doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk/_doordeck_headless_sdk.pyd \
            doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk/doordeck_headless_sdk_wrap.c \
            doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk.dll \
            -I ${{ env.Python3_ROOT_DIR }}/include -L ${{ env.Python3_ROOT_DIR }}/libs -lpython312

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v${{ steps.version_info.outputs.version }} --title "Release v${{ steps.version_info.outputs.version }}" --verify-tag --generate-notes