name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - v*.*.*
  pull_request:
    branches:
      - 'main'

jobs:
  release:
    name: Releases
    runs-on: macos-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "Doordeck Development"
          git config --global user.email "development@doordeck.com"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Install SWIG
        run: brew install swig

      - name: Install mingw-w64
        run: brew install mingw-w64

      - name: Install twine
        run: pip install twine

      - name: Setup python build
        run: python -m pip install build

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Tag for release (if on main)
        if: github.ref == 'refs/heads/main'
        run: ./gradlew final -x test

      - name: Parse release version
        id: version_info
        run: echo version=$(./gradlew properties -q -Prelease.useLastTag=true | grep "version:" | awk '{print $2}') >> "$GITHUB_OUTPUT"

      - name: Build mingw binaries
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew mingwX64Binaries
          
          # Adjust generated header
          sed -i '' \
            -e 's/_\$$/_/g' \
            -e 's/\$//g' \
          "doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk_api.h"

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./gradlew -Prelease.useLastTag=true pythonPack
          
          # Download python for windows
          curl -LO https://www.python.org/ftp/python/3.13.2/python-3.13.2-embed-amd64.zip
          mv python-3.13.2-embed-amd64.zip doordeck-sdk/build/bin/mingwX64/python
          unzip doordeck-sdk/build/bin/mingwX64/python/python-3.13.2-embed-amd64.zip -d doordeck-sdk/build/bin/mingwX64/python/windows-python
          
          swig -python -D_MSC_VER -o doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk_wrap.c \
            -outdir doordeck-sdk/build/bin/mingwX64/python/src/doordeck_headless_sdk \
            doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk.i
          
          x86_64-w64-mingw32-gcc -shared -o doordeck-sdk/build/bin/mingwX64/python/src/doordeck_headless_sdk/_doordeck_headless_sdk.pyd \
            doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk_wrap.c \
            doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk.dll \
            -I $(python3 -c "import sysconfig; print(sysconfig.get_paths()['include'])") \
            -L doordeck-sdk/build/bin/mingwX64/python/windows-python \
            -lpython313

          python -m build doordeck-sdk/build/bin/mingwX64/python

          twine upload --verbose --repository testpypi doordeck-sdk/build/bin/mingwX64/python/dist/*

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v${{ steps.version_info.outputs.version }} --title "Release v${{ steps.version_info.outputs.version }}" --verify-tag --generate-notes