name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - v*.*.*
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check SPM publication
        id: check_spm_publication
        run: |
          HTTP_STATUS=$(curl -LI https://cdn.doordeck.com/xcframework/v1.0.0/DoordeckSDK.xcframework.zip -o /dev/null -w '%{http_code}\n' -s)
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "spmPublished=true" >> "$GITHUB_OUTPUT"
          else
            echo "spmPublished=false" >> "$GITHUB_OUTPUT"
          fi
          'echo value is: $HTTP_STATUS'

      - name: Display SPM Publication Value
        run: 'echo The value of spmPublished is: ${{steps.check_spm_publication.outputs.spmPublished}}'